Change gemspec to require parser=2.6.3
* The parser gem started to emit a differently shaped
  procarg0 AST node in versions >= 2.6.4
* Mutant depends on unparser ~> 0.4.5 which depends on
  parser ~> 2.6.3
* Nail mutant's dependency to parser=2.6.3 until the
  change in AST is handled by downstream dependencies.
* See https://github.com/mbj/mutant/issues/970

* Add core/string/encode_spec.rb to rubyspec corpus exclusions.
  Avoid the following in rubyspec/core/string/encode_spec.rb:65
  error: literal contains escape sequences incompatible with UTF-8